Repository MIT-Emerging-Talent/ET6-CDSP-group-08-repo, pull requests merged in 2025-06, with the labels that each got.

#6 Constraints
  collaboration/constraints.md
Labels: documentation

#13 Update main
  collaboration/guide/0_repository_setup.md
  collaboration/retrospectives/0_cross_cultural_collaboration.md
  collaboration/retrospectives/1_problem_identification.md
  collaboration/retrospectives/2_data_collection.md
  collaboration/retrospectives/3_data_analysis.md
  collaboration/retrospectives/4_communicating_results.md
  collaboration/retrospectives/5_final_presentation.md
  collaboration/retrospectives/README.md
  collaboration/retrospectives/_template.md
Labels: enhancement

#10 Update from the main repository
  collaboration/guide/0_repository_setup.md
  collaboration/retrospectives/0_cross_cultural_collaboration.md
  collaboration/retrospectives/1_problem_identification.md
  collaboration/retrospectives/2_data_collection.md
  collaboration/retrospectives/3_data_analysis.md
  collaboration/retrospectives/4_communicating_results.md
  collaboration/retrospectives/5_final_presentation.md
  collaboration/retrospectives/README.md
  collaboration/retrospectives/_template.md
Labels: enhancement

#7 Learning goals
  collaboration/learning_goals.md
Labels: documentation

#20 Added my individual retrospectives for milestone0
  collaboration/retrospectives/0_cross_cultural_collaboration.md
Labels: documentation

#24 Added contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#26 Milestone1 progress
  0_domain_study/README.md
  0_domain_study/progress.md
Labels: documentation

#43 M1 Main readme
  README.md
Labels: enhancement

#50 fix formatting
  notes/05meeting_minutes.md
Labels: Fix errors

#53 Main readme
  README.md
Labels: documentation

#60 offgrid raw dataset along with its documentation
  1_datasets/README.md
  1_datasets/raw_data/IRENA_OFGStats.raw.xlsx
Labels: documentation

#57 added the raw datasets to the 1_datasets folder
  1_datasets/raw_data/IRENA_Stats_extract_2025_H1_raw.xlsx
  1_datasets/raw_data/UN_Comtrade_imports_dataset_raw.xlsx
Labels: documentation

#66 M2 cleaning scripts for the offgrid dataset
  1_datasets/README.md
  1_datasets/cleaned_data/IRENA_OFGStats.cleaned.xlsx
  2_data_preparation/IRENA_OFG_cleaned.ipynb
Labels: Code

#63 M2 Non technical explanation of Domain Modeling
  1_datasets/README.md
  1_datasets/non_tech_exp_of_domain_modeling.md
Labels: documentation

#70 Comtrade data clean
  1_datasets/README.md
  1_datasets/cleaned_data/UN_comtrade_clean_dataset.xlsx
  2_data_preparation/UN_comtrade_data_cleaning.ipynb
Labels: documentation, Code

#71 Script documentation
  1_datasets/cleaned_data/IRENA_ONGRIDStats.cleaned.xlsx
  2_data_preparation/IRENA_ONG_cleaned.ipynb
  2_data_preparation/README.md
  README.md
Labels: documentation, Code

#74 Add Offgrid dataset preparation documenation
  2_data_preparation/README.md
Labels: documentation
