Repository MIT-Emerging-Talent/ET6-CDSP-group-08-repo, pull requests merged in 2025-07, with the labels that each got.

#79 Update 2_data_collection.md
  collaboration/retrospectives/2_data_collection.md
Labels: documentation

#84 Update the main readme - added data collection
  README.md
Labels: documentation

#88 updated main Readme
  README.md
Labels: documentation

#95 added years 2000 to 2006 to UN Comtrade raw data
  1_datasets/README.md
  1_datasets/raw_data/UN_Comtrade_imports_dataset_raw.xlsx
Labels: documentation, enhancement

#101 Comparison analysis
  4_data_analysis/data_comparison_analysis/comparison_analysis.ipynb
  4_data_analysis/data_comparison_analysis/non_tech_explanation.md
  4_data_analysis/data_comparison_analysis/tech_explanation.md
Labels: documentation, Code

#102 Phases analysis
  .vscode/excel-pq-symbols/excel-pq-symbols.json
  .vscode/settings.json
  1_datasets/cleaned_data/ONG_conflictcountriesonly.xlsx
  2_data_preparation/README.md
  3_data_exploration/IRENA_ONG_explore_1.ipynb
  3_data_exploration/IRENA_ONG_explore_2.ipynb
  3_data_exploration/README.md
  4_data_analysis/README.md
  4_data_analysis/phases_analysis.ipynb
  4_data_analysis/phases_analysis/1.phases_analysis.ipynb
  4_data_analysis/phases_analysis/non_tech_exp.md
  4_data_analysis/phases_analysis/output_graphs/Average Installed Capacity (Total Renewable) by Conflict Phase.png
  4_data_analysis/phases_analysis/output_graphs/Average Solar Capacity by Conflict Phase - Ongrid and Off grid per country.png
  4_data_analysis/phases_analysis/output_graphs/Average Solar Capacity by Conflict Phase and Economic Status (excluding Ukraine).png
  4_data_analysis/phases_analysis/output_graphs/Average Solar Capacity by Conflict Phase and Economic Status per country.png
  4_data_analysis/phases_analysis/output_graphs/Average Solar Capacity by Conflict Phase and Grid Type in Ukraine.png
  4_data_analysis/phases_analysis/output_graphs/Average Solar Capacity by Conflict Phase and Grid Type.png
  4_data_analysis/phases_analysis/output_graphs/Average Solar PV Capacity by Conflict Phase per country- stacked barchart.png
  4_data_analysis/phases_analysis/output_graphs/Average Solar PV Capacity by Conflict Phases with and without Ukraine.png
  4_data_analysis/phases_analysis/output_graphs/Average Solar PV Capacity by Conflict Phases.png
  4_data_analysis/phases_analysis/output_graphs/Heat map for countries with similar pattern.png
  4_data_analysis/phases_analysis/output_graphs/Low Capacity vs low capacity countries soalr adoption.png
  4_data_analysis/phases_analysis/output_graphs/Offgrid Solar adoption in past 25 years in 9 conflict countries.png
  4_data_analysis/phases_analysis/output_graphs/Ongrid Solar adoption in past 25 years in 9 conflict countries.png
  4_data_analysis/phases_analysis/output_graphs/Regression.. Effect of Conflict on Solar Growth Rate.png
  4_data_analysis/phases_analysis/output_graphs/Solar Energy Analysis by Year.png
  4_data_analysis/phases_analysis/tech_exp.md
Labels: Code

#109 fixed some links in main README
  README.md
Labels: documentation, enhancement

#107 added my individual retrospective for milestone 3
  collaboration/retrospectives/3_data_analysis.md
Labels: documentation

#112 Update the main readme
  0_domain_study/README.md
  0_domain_study/progress.md
  README.md
Labels: enhancement

#114 M4 Meeting Minutes 11
  notes/11meeting_minutes.md
Labels: documentation, Meeting Agenda

#113 update and enhancement
  4_data_analysis/README.md
  4_data_analysis/output_graphs/Average Installed Capacity (Total Renewable) by Conflict Phase.png
  4_data_analysis/output_graphs/Average Solar Capacity by Conflict Phase - Ongrid and Off grid per country.png
  4_data_analysis/output_graphs/Average Solar Capacity by Conflict Phase and Economic Status (excluding Ukraine).png
  4_data_analysis/output_graphs/Average Solar Capacity by Conflict Phase and Economic Status per country.png
  4_data_analysis/output_graphs/Average Solar Capacity by Conflict Phase and Grid Type in Ukraine.png
  4_data_analysis/output_graphs/Average Solar Capacity by Conflict Phase and Grid Type.png
  4_data_analysis/output_graphs/Average Solar PV Capacity by Conflict Phase per country- stacked barchart.png
  4_data_analysis/output_graphs/Average Solar PV Capacity by Conflict Phases with and without Ukraine.png
  4_data_analysis/output_graphs/Average Solar PV Capacity by Conflict Phases.png
  4_data_analysis/output_graphs/Heat map for countries with similar pattern.png
  4_data_analysis/output_graphs/Low Capacity vs low capacity countries soalr adoption.png
  4_data_analysis/output_graphs/Offgrid Solar adoption in past 25 years in 9 conflict countries.png
  4_data_analysis/output_graphs/Ongrid Solar adoption in past 25 years in 9 conflict countries.png
  4_data_analysis/output_graphs/Regression.. Effect of Conflict on Solar Growth Rate.png
  4_data_analysis/output_graphs/Solar Adoption Intensity -USD-GDP per capita- by Conflict Group.png
  4_data_analysis/output_graphs/Solar Energy Analysis by Year.png
  4_data_analysis/output_graphs/Solar Product Imports over time by Conflct Group.png
  4_data_analysis/output_graphs/Solar Product Mix by Conflict Geoup (%).png
  4_data_analysis/output_graphs/Sudan- Normalized Off-Grid Solar vs Ongrid Solar.png
  4_data_analysis/output_graphs/Ukraine- Normalized Imports vs Ongrid Solar.png
  4_data_analysis/phases_analysis/1.phases_analysis.ipynb
  README.md
Labels: enhancement, in progress
